Qapi/urls.py
from django.urls import path
from .views import SubAPIView, QuizAPIView, AnsAPIView, ResAPIView


urlpatterns = [
    path('', SubAPIView.as_view(), name='subAPI'),
    path('quiz', QuizAPIView.as_view(), name='quizAPI'),
    path('answer', AnsAPIView.as_view(), name='ansAPI'),
    path('result', ResAPIView.as_view(), name='resAPI'),
]

mySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('site_api/', include('Qapi.urls'), name='site_api'),
]

polls/urls.py
from django.urls import path
from polls.views import IndexView, savollar, check, ResultListView
app_name = 'polls'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('questions/<int:category_id>/', savollar, name='questions'),
    path('check/', check, name='check'),
    path('user_account/', ResultListView.as_view(), name='user_account'),
]

Qapi/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    nomi = models.CharField(max_length=45)

    def __str__(self):
        return self.nomi


class Questions(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    quiz_text = models.CharField(max_length=500)

    def __str__(self):
        return self.quiz_text


class Choice(models.Model):
    questions = models.ForeignKey(Questions, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=150)
    correct = models.BooleanField()

    def __str__(self):
        return self.answer_text


class Result(models.Model):
    subject = models.ForeignKey(Category, on_delete=models.CASCADE)
    users = models.ForeignKey(User, on_delete=models.CASCADE)
    result = models.FloatField(default=0.0)

Qapi/views.py
from rest_framework.generics import ListAPIView
from polls.models import Category, Questions, Choice, Result
from .serializers import FanSerializer, SavolSerializer, JavobSerializer, NatijaSerializer


class SubAPIView(ListAPIView):
    queryset = Category.objects.all()
    serializer_class = FanSerializer


class QuizAPIView(ListAPIView):
    queryset = Questions.objects.all()
    serializer_class = SavolSerializer


class AnsAPIView(ListAPIView):
    queryset = Choice.objects.all()
    serializer_class = JavobSerializer


class ResAPIView(ListAPIView):
    queryset = Result.objects.all()
    serializer_class = NatijaSerializer

polls/views.py
from django.shortcuts import render, HttpResponse
from polls.models import Questions, Choice, Category, Result
from django.views.generic import ListView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class IndexView(ListView):
    model = Category
    template_name = "polls/index.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(IndexView, self).dispatch(*args, **kwargs)


class ResultListView(ListView):
    template_name = 'polls/user_account.html'

    def get_queryset(self):
        return Result.objects.filter(users=self.request.user)

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ResultListView, self).dispatch(request, *args, **kwargs)


@login_required
def savollar(request, category_id):
    savol = Category.objects.get(pk=category_id)
    all_savollar = Questions.objects.filter(category=savol)
    return render(request, 'polls/questions.html', {'all_savollar': all_savollar, })


@login_required
def check(request):
    user = request.user
    answer = []
    questions_numb = []
    for key, value in request.GET.items():
        questions_numb.append(key)
        answer.append(int(value))

    questions_l = Questions.objects.filter(id__in=questions_numb)
    choices = Choice.objects.filter(id__in=answer)

    correct_answers = 0
    for ch in choices:
        if ch.correct:
            correct_answers += 1
    result = (correct_answers / len(answer) * 100)

    Result.objects.update_or_create(
        users=user, subject=questions_l[0].category,
        defaults={
            'users': user,
            'subject': questions_l[0].category,
            'result': result
        },
    )

    return render(request, 'polls/result.html',
                  {'questions_l': questions_l,
                   'answer': answer,
                   'result': result
                   })




polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body style=" background-image: linear-gradient(88deg, rgba(65,90,90,0.9), rgba(85, 80, 90, 0.9) ); " >
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<nav class="navbar navbar-dark navbar-dark bg-dark">
    <div class="container-fluid">
       <a href="{% url 'logout' %}"><button class="btn btn-outline-info">Log out</button></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleXxl" aria-controls="navbarsExampleXxl" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
<a href="{% url 'polls:user_account' %}"><button class="btn btn-outline-info">My Account</button></a>

      <div class="collapse navbar-collapse" id="navbarsExampleXxl">
        <ul class="navbar-nav me-auto mb-2 mb-xl-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownXxl" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu" aria-labelledby="dropdownXxl">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <form>
          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>
<div style="margin-top: 4px;" class="col-12">
    <div class="row">
        <div class="col-1">
        </div>
        <div class="col-10">
            {% block main %}

            {% endblock %}
        </div>
        <div class="col-1">

        </div>
    </div>
</div>


</body>
</html>

polls/templates/polls/index.html
{% extends './base.html' %}

{% block main %}

<h4 class="btn btn-warning"> Bilimingizni sinab ko'rish uchun fanni tanlang!</h4>
{% for fan in object_list %}
<div class="list-group">
    <a href="{% url 'polls:questions' fan.id %}" class="list-group-item list-group-item-action list-group-item-primary">
        {{ fan.nomi }}
    </a>
</div>

{% endfor %}

{% endblock %}

polls/templates/polls/questions.html
{% extends './base.html' %}

{% block main %}
<h2>Savollar</h2>
<form action="{% url 'polls:check' %}">
    {% for savol in all_savollar %}
    {{ savol.quiz_text }} <br>

    {% for javob in savol.choice_set.all %}
    <input type="radio" id="savol" name="{{ savol.id }}" value="{{ javob.id }}" required>
    <label for="savol">{{javob.answer_text}} </label><br>
    {% endfor %}
    <hr>
    {% endfor %}

    <input type="submit" value="OK">
</form><br>
    <a style="text-decoration:none;" href="{% url 'polls:index' %}"><button>Home</button></a>
{% endblock %}

polls/templates/polls/result.html
{% extends './base.html' %}

{% block main %}
<a href="{% url 'polls:user_account' %}"><button>My Account</button></a>
<dl>
    {% for question in questions_l %}
    <dt>
        <p>
            {{ forloop.counter }}.{{ question.quiz_text }}
        </p>
    </dt>
    {% for choice in question.choice_set.all %}
    {% if choice.correct %}
    <dd style="color: green;">
        <strong>
            {{ choice.answer_text }}
        </strong>
    </dd>
    {% elif choice.id in answer %}
    <dd style="color:red;">
        {{ choice.answer_text }}
    </dd>
    {% else %}
    <dd>
        {{ choice.answer_text }}
    </dd>
    {% endif %}
    {% endfor %}
    <hr>
    {% endfor %}
    <a style="text-decoration:none;" href="{% url 'polls:index' %}"><button>Home </button></a>
</dl>


{% endblock %}

polls/templates/polls/user_account.html
{% extends './base.html' %}

{% block main %}
<div class="card text-center">
     <div class="card-header">
         <h1>
     Natijalar
             </h1>
  </div>
 {% if object_list %}
 {% for object in object_list %}
  <div class="card-body">
    <h3 style="color:Green;" class="card-title">
    {{ object.subject }} </h3>
    <p class="card-text">Sizning <strong style="color:blue;">{{ object.subject }}</strong> fani bo'yicha eng yuqori natijangiz: <strong>{{ object.result|floatformat:2 }}%</strong></p>
    <a href="{% url 'polls:questions' object.subject.id %}" class="btn btn-primary">Qayta urinish</a>
    <a href="{% url 'polls:index' %}"><button class="btn btn-primary">Home</button></a>
      <hr>
  </div>
    {% endfor %}
    </div>
    {% else %}
    <p class="card-text">
        Siz xali xech qanday fandan test topshirmadingiz
    </p>
    <a href="{% url 'polls:index' %}"><button>Home</button></a>
    <hr>
    {% endif %}

{% endblock %}